---
AWSTemplateFormatVersion: '2010-09-09'

Description: "Creates an s3 static website bucket for a given 'RootDomainName'"

Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String

Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - www.${Domain}
        - Domain: !Ref RootDomainName
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket
  RootBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # - Effect: Allow
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${RootBucket.Arn}/*'
            # CF Distribution ARNs have to be manually constructed
            Condition:
              IpAddress:
                AWS:SourceIp:
                  - 173.245.48.0/20
                  - 103.21.244.0/22
                  - 103.22.200.0/22
                  - 103.31.4.0/22
                  - 141.101.64.0/18
                  - 108.162.192.0/18
                  - 190.93.240.0/20
                  - 188.114.96.0/20
                  - 197.234.240.0/22
                  - 198.41.128.0/17
                  - 162.158.0.0/15
                  - 104.16.0.0/13
                  - 104.24.0.0/14
                  - 172.64.0.0/13
                  - 131.0.72.0/22
                  - 2400:cb00::/32
                  - 2606:4700::/32
                  - 2803:f800::/32
                  - 2405:b500::/32
                  - 2405:8100::/32
                  - 2a06:98c0::/29
                  - 2c0f:f248::/32

Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
  WebsiteURLWithoutProtocol:
    Value: !Join ['', !Split ['http://', !GetAtt RootBucket.WebsiteURL]]
    Description: URL without protocol for website hosted on S3
